- name: Install common packages needed for all services and administration
  apt: pkg={{ item }} state=present update-cache=yes cache_valid_time=86400
  with_items:
  - joe
# This sets up finnish locales for databases too
  - language-pack-fi
  - zabbix-agent
# This is actually redundant, but perhaps it might help in the future?
  - postgresql
  - postgresql-9.1-postgis
# Ansible requires this, thus it is always needed
  - python-psycopg2
  - unattended-upgrades