- name: Disallow passing locale information over SSH
  lineinfile: dest=/etc/ssh/sshd_config regexp=^AcceptEnv state=absent
- name: Restart sshd
  service: name=ssh state=restarted

- name: Install common packages needed for all services and administration
  apt: pkg={{ item }} state=present update-cache=yes cache_valid_time=86400
  with_items:
  - joe
# This sets up finnish locales for databases too
  - language-pack-fi
  - zabbix-agent
  - postgresql
# Ansible requires this, thus it is always needed
  - python-psycopg2
