---
- name: Adding PPA repository for Openstreetmap-tools
  apt_repository: repo='ppa:kakrueger/openstreetmap' state=present

- name: Add UbuntuGIS PPA (unstable version for 13.10)
  apt_repository: repo='ppa:ubuntugis/ubuntugis-unstable' state=present          

# osm2pgsql brings (through "recommends") in openstreetmap-postgis-db-setup
# which, by default, automatically creates a database and user. The script
# is useful, but we want different defaults
- name: Disable automatic OSM database & user creation
  tags: java
  shell: echo debconf openstreetstreetmap-postgis-db-setup/initdb select false | sudo debconf-set-selections

- name: Installing osm2pgsql
  apt: pkg={{ item }} state=present update-cache=yes cache_valid_time=86400
  with_items:
  - osm2pgsql
  - openstreetmap-postgis-db-setup

- name: Testing for existence of OSM database
  sudo_user: postgres
  command: psql -c '\dt' {{ osm_database }}
  register: osm_database_status
  ignore_errors: yes

- debug: var=osm_database_status

- include: osm-data-setup-import.yml
  when: osm_database_status.rc != 0 or force_osm
