- name: Remove existing database (if any)
  sudo_user: postgres
  postgresql_db: name={{ osm_database }}
                 state=absent

- name: Remove existing database user (if any)
  sudo_user: postgres
  postgresql_user: name={{ servicemap_system_user }}
                   state=absent

# This script does a sudo to postgres internally, as it has been originally
# intended to run from Debian packaging
- name: Creating database & user for OSM data
  shell: DBOWNER={{ servicemap_system_user }} DBNAME={{ osm_database }} /usr/bin/install-postgis-osm-db.sh

# This does not download new data, if the file already exists
- name: Downloading OSM-data from download.geofabrik.de
  get_url: url=http://download.geofabrik.de/europe/finland-latest.osm.pbf
           dest=/home/{{ deployment_user }}/finland-latest.osm.pbf
           mode=0444
# This is not used at the moment, as the data should only be loaded once
#  register: osm_download_status

- name: Importing OSM data (this step will take considerable time)
  sudo_user: "{{ servicemap_system_user }}"
  shell: osm2pgsql -s -C {{ osm2pgsql_cache_size }} -d {{ osm_database }} /home/{{ deployment_user }}/finland-latest.osm.pbf

- name: Updating time stamp for import
  sudo_user: "{{ servicemap_system_user }}"
  command: touch /home/{{ servicemap_system_user }}/timestamps/osm_import
