- name: PostgreSQL-standby | Test whether replication is already setup
  command: psql -x -c 'SELECT pg_is_in_recovery()'
  register: replication_running
- debug: var=replication_running
- include: setup_replication.yml
  when: replication_running.stdout.find('pg_is_in_recovery | t') == -1
