---
- name: Installing necessary packages (Tomcat7 and unzip)
  apt: pkg={{ item }} state=present update-cache=yes cache_valid_time=86400
  with_items:
  - tomcat7
  - unzip

# Destination includes the filename as this causes Ansible to re-downloaded
# only if necessary
- name: Downloading Geoserver version {{ geoserver_version }}
  get_url: url=http://sourceforge.net/projects/geoserver/files/GeoServer/{{ geoserver_version }}/geoserver-{{ geoserver_version }}-war.zip
           dest=/home/{{ deployment_user }}/geoserver-{{ geoserver_version }}-war.zip
           sha256sum={{ geoserver_sha256 }}
           mode=0440
  register: geoserver_download_status

- include: geoserver-install.yml
  when: geoserver_download_status|changed
